### ISSUE TITLE
application.yaml is missing RELEASE_VERSION parameter in tag v2.0.1

### ISSUE THREAD

**Issue by pmacik** [nodeshift-starters/nodejs-rest-http#122]
As required by https://github.com/fabric8io/osio-pipeline/pull/86

**Comment by pmacik** [comment]
This causes a Jenkins build ([v10-community](https://github.com/fabric8-launcher/launcher-booster-catalog/blob/master/nodejs/v10-community/rest-http/booster.yaml)) to fail:
```
First time build. Skipping changelog.
fatal: bad object 9be2751f7c9a3396223e7bf8743951e236e3c0cf
[Pipeline] fileExists
[Pipeline] readYaml
[Pipeline] echo
Missing parameter RELEASE_VERSION in openshift template
[Pipeline] error
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: Invalid template, please refer below link to fix the application template (application.yaml) and build again 
https://github.com/fabric8io/osio-pipeline#processtemplate
Finished: FAILURE
```

**Comment by lholmquist** [comment]
yup,  looks like it was merged in after that 2.0.1 release,  i'll create a new tag then

**Comment by lholmquist** [comment]
tag 2.1.0 should have that new param

**Comment by lholmquist** [comment]
this version is now part of the v81 tag of the launcher , https://github.com/fabric8-launcher/launcher-booster-catalog/commits/v81
