### ISSUE TITLE
The build is failing during test case

### ISSUE THREAD

**Issue by pnaik1** [nodeshift-starters/nodejs-rest-http#219]
The failure is due to the ESLint
 npm test

> nodejs-rest-http@4.0.0 pretest /home/pnaik/NODESHIFT/nodejs-rest-http
> eslint --ignore-path .gitignore .

Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find the config "standard" to extend from. Please check that the name of the config is correct.

The config "standard" was referenced from the config file in "/home/pnaik/NODESHIFT/nodejs-rest-http/node_modules/eslint-config-semistandard/index.js".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

**Comment by helio-frota** [comment]
@pnaik1 thank you for the report.

I downgraded locally to 14.x and got the following:

```
❯ npm t

> nodejs-rest-http@4.0.0 pretest /home/lm/code/nodejs-rest-http
> eslint --ignore-path .gitignore .


Oops! Something went wrong! :(

ESLint: 7.32.0
...
```

But this example is using 16.x and 18.x https://github.com/nodeshift-starters/nodejs-rest-http/blob/main/package.json#L15

And we had issues on the github action.

can you please update your node.js version, and sent the PR again with a new generated package-lock.json ?

**Comment by pnaik1** [comment]
Thank you , working with 16.x

**Comment by helio-frota** [comment]
great , let's close the issue then :+1:
